"""Set default value for type in Author model

Revision ID: eca2ab645178
Revises: 50e3758202b7
Create Date: 2025-03-06 10:46:41.948053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eca2ab645178'
down_revision = '50e3758202b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
